---
galaxy_info:
  author: TaskFlow DevOps
  description: Common system configuration and hardening
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - system
    - security
    - hardening
    - common

dependencies: []
