# TaskFlow - Local VMs Ansible Dynamic Inventory Template
# Generated by Terraform for local VirtualBox VMs

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=${ssh_key_path}
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3

# Project variables
project_name=taskflow
environment=local
domain_name=taskflow.local

# K3s variables
k3s_version=latest
k3s_channel=stable
k3s_token=${k3s_token}

# Docker variables
docker_version=latest
docker_compose_version=2.20.0

# Monitoring variables
prometheus_version=2.45.0
grafana_version=10.0.0

# Security variables
fail2ban_enabled=true
ufw_enabled=true
ssl_enabled=true

# Backup variables
backup_enabled=true
backup_retention_days=7

# Cost optimization
cost_optimization_enabled=true
schedule_shutdown=false
shutdown_time=22:00
startup_time=08:00

# Local VMs hosts
[local_vms:children]
k3s_master
k3s_workers
bastion

[k3s_master]
${master_ip}

[k3s_workers]
${worker1_ip}
${worker2_ip}

[bastion]
${bastion_ip}

# Group variables
[k3s_master:vars]
ansible_host=${master_ip}
node_role=master
k3s_token=${k3s_token}

[k3s_workers:vars]
ansible_host=${worker1_ip}
node_role=worker
k3s_master_ip=${master_ip}
k3s_token=${k3s_token}

[bastion:vars]
ansible_host=${bastion_ip}
node_role=bastion

# Local VMs specific variables
[local_vms:vars]
cloud_provider=local
vm_provider=virtualbox
network_type=bridged

# Development environment
[dev:children]
k3s_master
k3s_workers
bastion

[dev:vars]
environment=dev
monitoring_enabled=true
logging_enabled=true
backup_enabled=true

# Monitoring hosts
[monitoring:children]
k3s_master
k3s_workers

[monitoring:vars]
prometheus_enabled=true
grafana_enabled=true
node_exporter_enabled=true
kube_state_metrics_enabled=true

# Database hosts
[database:children]
k3s_master

[database:vars]
postgresql_enabled=true
postgresql_version=15
postgresql_port=5432
postgresql_user=taskflow_user
postgresql_database=taskflow

# Application hosts
[application:children]
k3s_master
k3s_workers

[application:vars]
app_name=taskflow
app_namespace=taskflow
app_replicas=2
app_image=taskflow:latest

# Security hosts
[security:children]
k3s_master
k3s_workers
bastion

[security:vars]
firewall_enabled=true
fail2ban_enabled=true
ssl_enabled=true
backup_enabled=true
