---
galaxy_info:
  author: TaskFlow DevOps
  description: Security hardening and configuration
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - security
    - hardening
    - firewall
    - ssl
    - fail2ban

dependencies: []
