# TaskFlow - Ansible Dynamic Inventory Template
# Generated by Terraform for Oracle Cloud infrastructure
# This inventory file is automatically created when Terraform applies

[all:vars]
ansible_user=opc
ansible_ssh_private_key_file=${ssh_key_path}
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3

# K3s variables
k3s_token=${k3s_token}

[k3s_master]
${master_ip}

[k3s_workers]
${worker1_ip}
${worker2_ip}

[bastion]
${bastion_ip}

[k3s_cluster:children]
k3s_master
k3s_workers

[oracle_cloud:children]
k3s_master
k3s_workers
bastion

# Group variables
[k3s_master:vars]
ansible_host=${master_ip}
node_role=master
k3s_token=${k3s_token}

[k3s_workers:vars]
ansible_host=${worker1_ip}
node_role=worker
k3s_master_ip=${master_ip}
k3s_token=${k3s_token}

[bastion:vars]
ansible_host=${bastion_ip}
node_role=bastion

# Connection information
# Master: ssh -i ${ssh_key_path} opc@${master_ip}
# Worker1: ssh -i ${ssh_key_path} opc@${worker1_ip}
# Worker2: ssh -i ${ssh_key_path} opc@${worker2_ip}
# Bastion: ssh -i ${ssh_key_path} opc@${bastion_ip}