apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: taskflow-backend
  labels:
    app: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-registry/taskflow-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
            # Use external managed PostgreSQL (Supabase, Railway, etc.)
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: external-db-credentials
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: external-db-credentials
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: external-db-credentials
                  key: database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: external-db-credentials
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: external-db-credentials
                  key: password
            - name: DB_SSL
              value: "true"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt_secret
            - name: JWT_EXPIRES_IN
              value: "7d"
            - name: CORS_ORIGIN
              value: "https://taskflow.vercel.app"
            # Optional: External Redis (Upstash, Railway, etc.)
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: external-redis-credentials
                  key: url
                  optional: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
