---
# Default variables for postgresql role

# PostgreSQL version
postgresql_version: "15"

# PostgreSQL service
postgresql_service_enabled: true
postgresql_service_state: started

# PostgreSQL configuration
postgresql_listen_addresses: "localhost"
postgresql_port: 5432
postgresql_max_connections: 100
postgresql_shared_buffers: "128MB"
postgresql_effective_cache_size: "4GB"
postgresql_maintenance_work_mem: "64MB"
postgresql_checkpoint_completion_target: 0.9
postgresql_wal_buffers: "16MB"
postgresql_default_statistics_target: 100
postgresql_random_page_cost: 1.1
postgresql_effective_io_concurrency: 200
postgresql_work_mem: "4MB"
postgresql_min_wal_size: "1GB"
postgresql_max_wal_size: "4GB"

# Database configuration
postgresql_databases:
  - name: taskflow
    encoding: "UTF-8"
    lc_collate: "en_US.UTF-8"
    lc_ctype: "en_US.UTF-8"

# User configuration
postgresql_users:
  - name: taskflow_user
    password: "{{ lookup('env', 'DB_PASSWORD') | default('changeme', true) }}"
    database: taskflow
    priv: "ALL"

# Backup configuration
postgresql_backup_enabled: true
postgresql_backup_dir: "/var/backups/postgresql"
postgresql_backup_retention_days: 7
postgresql_backup_schedule:
  hour: "2"
  minute: "0"

# pg_hba.conf configuration
postgresql_hba_entries:
  - type: local
    database: all
    user: postgres
    method: peer
  - type: local
    database: all
    user: all
    method: peer
  - type: host
    database: all
    user: all
    address: "127.0.0.1/32"
    method: scram-sha-256
  - type: host
    database: all
    user: all
    address: "::1/128"
    method: scram-sha-256

# Extensions to enable
postgresql_extensions:
  - pg_stat_statements
  - pgcrypto

# Replication (if needed)
postgresql_replication_enabled: false
