blank_issues_enabled: true
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/YOUR_USERNAME/TaskFlow/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/YOUR_USERNAME/TaskFlow/tree/main/docs
    about: Read the comprehensive documentation
  - name: 🆘 Troubleshooting Guide
    url: https://github.com/YOUR_USERNAME/TaskFlow/blob/main/docs/TROUBLESHOOTING.md
    about: Common issues and solutions
