# TaskFlow - Common Role Tasks
# Common system configuration for all hosts

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install essential packages
  apt:
    name:
      - curl
      - wget
      - git
      - vim
      - htop
      - unzip
      - jq
      - ufw
      - fail2ban
      - unattended-upgrades
      - ntp
    state: present

- name: Configure UFW firewall
  ufw:
    state: enabled
    policy: deny
    direction: incoming
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "22"    # SSH
    - "80"    # HTTP
    - "443"   # HTTPS
    - "6443"  # Kubernetes API
    - "10250" # Kubelet
    - "30000:32767" # NodePort range

- name: Configure fail2ban
  copy:
    content: |
      [DEFAULT]
      bantime = 3600
      findtime = 600
      maxretry = 3
      
      [sshd]
      enabled = true
      port = ssh
      filter = sshd
      logpath = /var/log/auth.log
      maxretry = 3
    dest: /etc/fail2ban/jail.local
    mode: '0644'
  notify: restart fail2ban

- name: Enable fail2ban
  systemd:
    name: fail2ban
    enabled: yes
    state: started

- name: Configure automatic security updates
  copy:
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      APT::Periodic::AutocleanInterval "7";
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: '0644'

- name: Configure NTP
  copy:
    content: |
      server 0.pool.ntp.org
      server 1.pool.ntp.org
      server 2.pool.ntp.org
      server 3.pool.ntp.org
    dest: /etc/ntp.conf
    mode: '0644'
  notify: restart ntp

- name: Enable NTP
  systemd:
    name: ntp
    enabled: yes
    state: started

- name: Configure swap
  copy:
    content: |
      vm.swappiness=10
      vm.vfs_cache_pressure=50
    dest: /etc/sysctl.d/99-swap.conf
    mode: '0644'

- name: Apply sysctl settings
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  loop:
    - { key: "vm.swappiness", value: "10" }
    - { key: "vm.vfs_cache_pressure", value: "50" }
    - { key: "net.bridge.bridge-nf-call-iptables", value: "1" }
    - { key: "net.ipv4.ip_forward", value: "1" }

- name: Create taskflow user
  user:
    name: taskflow
    groups: sudo
    shell: /bin/bash
    state: present

- name: Set up log rotation
  copy:
    content: |
      /var/log/taskflow/*.log {
        daily
        rotate 7
        compress
        delaycompress
        missingok
        notifempty
      }
    dest: /etc/logrotate.d/taskflow
    mode: '0644'

- name: Create log directory
  file:
    path: /var/log/taskflow
    state: directory
    mode: '0755'
    owner: root
    group: root
