---
galaxy_info:
  author: TaskFlow DevOps
  description: Install and configure Prometheus and Grafana monitoring stack
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - monitoring
    - prometheus
    - grafana
    - observability
    - metrics

dependencies: []
