# Prometheus Alert Rules for TaskFlow
# Define alerts for various failure scenarios and performance issues

groups:
  # Application Health Alerts
  - name: application_health
    interval: 30s
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
          category: availability
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.job }} on {{ $labels.instance }} has been down for more than 1 minute."

      - alert: HighErrorRate
        expr: |
          (
            sum(rate(http_requests_total{status_code=~"5.."}[5m])) by (job)
            /
            sum(rate(http_requests_total[5m])) by (job)
          ) > 0.05
        for: 5m
        labels:
          severity: warning
          category: errors
        annotations:
          summary: "High error rate detected on {{ $labels.job }}"
          description: "Error rate is {{ $value | humanizePercentage }} on {{ $labels.job }}"

      - alert: HighResponseTime
        expr: |
          histogram_quantile(0.95,
            sum(rate(http_request_duration_seconds_bucket[5m])) by (le, job)
          ) > 1
        for: 5m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "High response time on {{ $labels.job }}"
          description: "95th percentile response time is {{ $value }}s on {{ $labels.job }}"

  # Resource Usage Alerts
  - name: resource_usage
    interval: 30s
    rules:
      - alert: HighCPUUsage
        expr: process_cpu_seconds_total > 0.8
        for: 5m
        labels:
          severity: warning
          category: resources
        annotations:
          summary: "High CPU usage on {{ $labels.job }}"
          description: "CPU usage is above 80% on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: |
          (
            process_resident_memory_bytes
            /
            (node_memory_MemTotal_bytes or process_virtual_memory_max_bytes)
          ) > 0.9
        for: 5m
        labels:
          severity: warning
          category: resources
        annotations:
          summary: "High memory usage on {{ $labels.job }}"
          description: "Memory usage is above 90% on {{ $labels.instance }}"

      - alert: DiskSpaceLow
        expr: |
          (
            node_filesystem_avail_bytes{mountpoint="/"}
            /
            node_filesystem_size_bytes{mountpoint="/"}
          ) < 0.1
        for: 5m
        labels:
          severity: warning
          category: resources
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Disk space is below 10% on {{ $labels.instance }}"

  # Database Alerts
  - name: database
    interval: 30s
    rules:
      - alert: HighDatabaseConnections
        expr: |
          sum(database_connections{state="active"}) by (instance)
          /
          sum(database_connections{state="total"}) by (instance)
          > 0.8
        for: 5m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "High database connection usage"
          description: "Database connection pool is above 80% on {{ $labels.instance }}"

      - alert: SlowQueries
        expr: rate(postgres_slow_queries_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
          category: database
        annotations:
          summary: "High number of slow queries"
          description: "Slow query rate is {{ $value }} per second on {{ $labels.instance }}"

  # Application-Specific Alerts
  - name: taskflow_alerts
    interval: 30s
    rules:
      - alert: HighTaskCreationRate
        expr: rate(tasks_created_total[5m]) > 100
        for: 5m
        labels:
          severity: info
          category: business
        annotations:
          summary: "Unusually high task creation rate"
          description: "Task creation rate is {{ $value }} per second"

      - alert: AuthenticationFailures
        expr: rate(auth_attempts_total{status="failure"}[5m]) > 5
        for: 5m
        labels:
          severity: warning
          category: security
        annotations:
          summary: "High authentication failure rate"
          description: "Authentication failures: {{ $value }} per second. Possible brute force attack."

      - alert: ActiveConnectionsHigh
        expr: active_connections > 100
        for: 5m
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "High number of active connections"
          description: "Active connections: {{ $value }}"

  # SSL/TLS Certificate Alerts
  - name: certificates
    interval: 1h
    rules:
      - alert: CertificateExpiringSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7
        for: 1h
        labels:
          severity: warning
          category: security
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.instance }} expires in {{ $value | humanizeDuration }}"

      - alert: CertificateExpired
        expr: probe_ssl_earliest_cert_expiry - time() < 0
        for: 1m
        labels:
          severity: critical
          category: security
        annotations:
          summary: "SSL certificate has expired"
          description: "SSL certificate for {{ $labels.instance }} has expired"

  # Kubernetes Alerts (when running on K8s)
  - name: kubernetes
    interval: 30s
    rules:
      - alert: PodCrashLooping
        expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
        for: 5m
        labels:
          severity: warning
          category: kubernetes
        annotations:
          summary: "Pod {{ $labels.pod }} is crash looping"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is restarting frequently"

      - alert: PodNotReady
        expr: sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"}) > 0
        for: 5m
        labels:
          severity: warning
          category: kubernetes
        annotations:
          summary: "Pod {{ $labels.pod }} not ready"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has been in {{ $labels.phase }} state for more than 5 minutes"

      - alert: NodeNotReady
        expr: kube_node_status_condition{condition="Ready",status="true"} == 0
        for: 5m
        labels:
          severity: critical
          category: kubernetes
        annotations:
          summary: "Node {{ $labels.node }} not ready"
          description: "Node {{ $labels.node }} has been in NotReady state for more than 5 minutes"

      - alert: HighPodCPU
        expr: |
          sum(rate(container_cpu_usage_seconds_total{pod!=""}[5m])) by (pod, namespace)
          /
          sum(kube_pod_container_resource_limits{resource="cpu"}) by (pod, namespace)
          > 0.9
        for: 5m
        labels:
          severity: warning
          category: kubernetes
        annotations:
          summary: "Pod {{ $labels.pod }} high CPU usage"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is using > 90% of its CPU limit"

      - alert: HighPodMemory
        expr: |
          sum(container_memory_working_set_bytes{pod!=""}) by (pod, namespace)
          /
          sum(kube_pod_container_resource_limits{resource="memory"}) by (pod, namespace)
          > 0.9
        for: 5m
        labels:
          severity: warning
          category: kubernetes
        annotations:
          summary: "Pod {{ $labels.pod }} high memory usage"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is using > 90% of its memory limit"
